### ISSUE TITLE
kingfisher error

### ISSUE THREAD

**Issue by yuzhenpeng** [wwood/kingfisher-download#11]
hello, wwood,

I used the kingfisher get some error. Could you help me, Thank you.

`kingfisher get -r ERR1739691 -m ena-ascp

07/17/2021 04:23:33 PM INFO: Attempting download method ena-ascp ..
07/17/2021 04:23:33 PM INFO: Using aspera ssh key file: $HOME/.aspera/connect/etc/asperaweb_id_dsa.openssh
07/17/2021 04:23:33 PM INFO: Querying ENA for FTP paths for ERR1739691..
Traceback (most recent call last):
  File "/public4/home/sc56340/miniconda3/bin/kingfisher", line 261, in <module>
    main()
  File "/public4/home/sc56340/miniconda3/bin/kingfisher", line 224, in main
    kingfisher.download_and_extract(
  File "/public4/home/sc56340/miniconda3/lib/python3.9/site-packages/kingfisher/__init__.py", line 213, in download_and_extract
    result = EnaDownloader().download_with_aspera(run_identifier, '.',
  File "/public4/home/sc56340/miniconda3/lib/python3.9/site-packages/kingfisher/ena.py", line 56, in download_with_aspera
    ftp_urls = self.get_ftp_download_urls(run_id)
  File "/public4/home/sc56340/miniconda3/lib/python3.9/site-packages/kingfisher/ena.py", line 20, in get_ftp_download_urls
    text = extern.run("curl --silent '{}'".format(query_url))
  File "/public4/home/sc56340/miniconda3/lib/python3.9/site-packages/extern/__init__.py", line 41, in run
    raise ExternCalledProcessError(process, command)
extern.ExternCalledProcessError: Command curl --silent 'https://www.ebi.ac.uk/ena/portal/api/filereport?accession=ERR1739691&result=read_run&fields=fastq_ftp' returned non-zero exit status 1.
STDERR was: b STDOUT was: b
`

**Comment by wwood** [comment]
Hi,

I'm hopefully soon going to release some fixes for things like this, but in the meantime does just simply rerunning it work? Sometimes ENA can be a bit finnicky.

**Comment by yuzhenpeng** [comment]
solved it. maybe my network problem

**Comment by yuzhenpeng** [comment]
By the way, can you set the ascp with `-k 1`, which support network outage for continuing download.

**Comment by wwood** [comment]
I set the default to `-k 2` so some checksum is used in case of file corruption, but thanks for the tip. You can change this also with `--ascp-args`.
