### ISSUE TITLE
AttributeError: 'float' object has no attribute 'split'

### ISSUE THREAD

**Issue by Johnsonzcode** [wwood/kingfisher-download#25]
Dear @wwood 
I am downloading batchs of SRA with kingfisher.
But there is always error like:
```
03/09/2023 11:30:56 AM INFO: Kingfisher v0.1.2
03/09/2023 11:30:56 AM INFO: Attempting download method ena-ascp for run ERR1346134 ..
03/09/2023 11:30:56 AM INFO: Using aspera ssh key file: /home/data/user01/Software/mambaforge/envs/sra_download/lib/python3.11/site-packages/kingfisher/data/asperaweb_id_dsa.openssh
03/09/2023 11:30:56 AM INFO: Querying ENA for FTP paths for ERR1346134..
Traceback (most recent call last):
  File "/home/user01/WORKSPACE/Software/mambaforge/envs/sra_download/bin/kingfisher", line 299, in <module>
    main()
  File "/home/user01/WORKSPACE/Software/mambaforge/envs/sra_download/bin/kingfisher", line 244, in main
    kingfisher.download_and_extract(
  File "/home/user01/WORKSPACE/Software/mambaforge/envs/sra_download/lib/python3.11/site-packages/kingfisher/__init__.py", line 47, in download_and_extract
    download_and_extract_one_run(run, **kwargs)
  File "/home/user01/WORKSPACE/Software/mambaforge/envs/sra_download/lib/python3.11/site-packages/kingfisher/__init__.py", line 306, in download_and_extract_one_run
    result = EnaDownloader().download_with_aspera(run_identifier, '.',
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user01/WORKSPACE/Software/mambaforge/envs/sra_download/lib/python3.11/site-packages/kingfisher/ena.py", line 71, in download_with_aspera
    report = self.get_ftp_download_urls(run_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user01/WORKSPACE/Software/mambaforge/envs/sra_download/lib/python3.11/site-packages/kingfisher/ena.py", line 47, in get_ftp_download_urls
    ftp_urls = row['fastq_ftp'].split(';')
               ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'float' object has no attribute 'split'
```
It seems to be ENA Querying API issue.
How could I solve it ?

Best wish
Johnsonz

**Comment by wwood** [comment]
Hi,

I believe this is an error specific to that run - e.g. yours fails for me, while the one in test_ena.py works - SRR12118866

You can see what is happening if you specify `--debug` since that prints the API response. I've changed the code so it is more graceful when it encounters this situation, so it can move onto other download methods if any are specified.

HTH?
Thanks, ben

**Comment by Johnsonzcode** [comment]
Appreciate so much. I will try.
