### ISSUE TITLE
Ena-ascp download gives 'Deprecated peer license' error 

### ISSUE THREAD

**Issue by mdehollander** [wwood/kingfisher-download#37]
It seems ascp downloads for ENA are not working anymore. At least at my end. I have tried with aspera connect version 4.1 and 4.2. This is what I get:

```
kingfisher get -m ena-ascp -r SRR616044
03/13/2024 03:53:13 PM INFO: Kingfisher v0.4.1
03/13/2024 03:53:13 PM INFO: Attempting download method ena-ascp for run SRR616044 ..
03/13/2024 03:53:13 PM INFO: Using aspera ssh key file: /usr/local/lib/python3.11/site-packages/kingfisher/data/asperaweb_id_dsa.openssh
03/13/2024 03:53:13 PM INFO: Querying ENA for FTP paths for SRR616044..
03/13/2024 03:53:13 PM INFO: Downloading 1 FTP read set(s): ftp.sra.ebi.ac.uk/vol1/fastq/SRR616/SRR616044/SRR616044.fastq.gz
03/13/2024 03:53:13 PM INFO: Running command: ascp -T -l 300m -P33001 -k 2 -i /usr/local/lib/python3.11/site-packages/kingfisher/data/asperaweb_id_dsa.openssh era-fasp@fasp.sra.ebi.ac.uk:/vol1/fastq/SRR616/SRR616044/SRR616044.fastq.gz .
03/13/2024 03:53:14 PM WARNING: Error downloading from ENA with ASCP: Command ascp -T -l 300m -P33001 -k 2 -i /usr/local/lib/python3.11/site-packages/kingfisher/data/asperaweb_id_dsa.openssh era-fasp@fasp.sra.ebi.ac.uk:/vol1/fastq/SRR616/SRR616044/SRR616044.fastq.gz . returned non-zero exit status 1.
STDERR was: b''STDOUT was: b'\r\nSession Stop  (Error: Failure processing peer license: Deprecated peer license)\n'
03/13/2024 03:53:14 PM WARNING: Method ena-ascp failed
Traceback (most recent call last):
  File "/usr/local/bin/kingfisher", line 323, in <module>
    main()
  File "/usr/local/bin/kingfisher", line 266, in main
    kingfisher.download_and_extract(
  File "/usr/local/lib/python3.11/site-packages/kingfisher/__init__.py", line 72, in download_and_extract
    download_and_extract_one_run(run, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/kingfisher/__init__.py", line 365, in download_and_extract_one_run
    raise Exception("No more specified download methods, cannot continue")
Exception: No more specified download methods, cannot continue
```

Is this a general error?

**Comment by wwood** [comment]
Seems like it is. I think this means aspera is no longer usable with ENA (whether using kingfisher or not). I'll raise a ticket with ENA support.

**Comment by mdehollander** [comment]
It has been fixed. See also this biostars thread https://www.biostars.org/p/9589973/#9590046 with a message from  Rasko Leinonen from EBI.

**Comment by wwood** [comment]
Thanks for being clean. Glad it sorted.

-\-------------
Ben Woodcroft
Group leader, Centre for Microbiome Research, QUT
________________________________
